//
//  NotificationSignals.swift
//  RISCC
//
//  Created by Jeevan Chaudhary on 18/03/2021.
//

import Foundation

let SIGNALKEY_APP_DID_ENTER_BACKGROUND              = "SIGNALKEY_APP_DID_ENTER_BACKGROUND"

let SIGNALKEY_APP_WILL_ENTER_FOREGROUND             = "SIGNALKEY_APP_WILL_ENTER_FOREGROUND"

let SIGNALKEY_INTERNET_CONNECTED                    = "SIGNALKEY_INTERNET_CONNECTED"

let SIGNALKEY_INTERNET_DISCONNECTED                 = "SIGNALKEY_INTERNET_DISCONNECTED"

let SIGNALKEY_SHOW_LEFT_MENU              = "SIGNALKEY_SHOW_LEFT_MENU"

let SIGNALKEY_REMOVE_LEFT_MENU            = "SIGNALKEY_SHOW_LEFT_MENU"
